# -*- coding: utf-8 -*-
"""MAS Problem 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1atTt5wbAvmqDSuQcinD8wY6gLa9uinSV
"""

# ============================================================
# PROBLEM 1 - FORMATION CONTROL OF RAGHU
# ============================================================

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt


# ============================================================
# STEP 1: ERDOS-RENYI COMMUNICATION GRAPH
# ============================================================

N = 20
p = 0.25

# Reproducibility
np.random.seed(42)

# Generate an Erdős-Rényi graph until it is connected
while True:

    G_graph = nx.erdos_renyi_graph(N, p)

    if nx.is_connected(G_graph):
        break


# Adjacency matrix
A = nx.to_numpy_array(G_graph)


# Print graph information
print("Number of agents:", N)
print("Edge probability:", p)
print("Number of edges:", G_graph.number_of_edges())
print("Graph connected:", nx.is_connected(G_graph))


# Plot communication graph
plt.figure(figsize=(8, 6))

pos = nx.spring_layout(
    G_graph,
    seed=42
)

nx.draw(
    G_graph,
    pos,
    with_labels=True,
    node_size=600
)

plt.title(
    f"Connected Erdos-Renyi Communication Graph\n"
    f"N={N}, p={p}"
)

plt.show()


# ============================================================
# STEP 2: RANDOM INITIAL POSITIONS
# ============================================================

X0 = np.random.uniform(
    low=-5,
    high=5,
    size=(N, 2)
)

print("\nInitial position matrix shape:", X0.shape)

print("\nInitial positions:")
print(X0)


# Plot initial positions
plt.figure(figsize=(7, 6))

plt.scatter(
    X0[:, 0],
    X0[:, 1],
    s=100
)

for i in range(N):

    plt.text(
        X0[i, 0] + 0.1,
        X0[i, 1] + 0.1,
        str(i)
    )


plt.xlabel("x position")
plt.ylabel("y position")

plt.title(
    "Random Initial Positions of 20 Agents"
)

plt.grid(True)
plt.axis("equal")

plt.show()


# ============================================================
# STEP 3: TARGET FORMATIONS
# R, A, G, H, U
# ============================================================


# ------------------------------------------------------------
# R - EXACTLY 20 POINTS
# ------------------------------------------------------------

R = np.array([
    # Vertical stem
    [0.0, 0.0],
    [0.0, 0.67],
    [0.0, 1.33],
    [0.0, 2.00],
    [0.0, 2.67],
    [0.0, 3.33],
    [0.0, 4.00],

    # Top
    [0.5, 4.0],
    [1.0, 4.0],
    [1.5, 4.0],
    [2.0, 4.0],

    # Right side
    [2.0, 3.3],
    [2.0, 2.7],
    [2.0, 2.3],

    # Middle
    [1.5, 2.0],
    [0.7, 2.0],

    # Diagonal leg
    [0.8, 1.6],
    [1.25, 1.1],
    [1.7, 0.55],
    [2.2, 0.0]
])


# ------------------------------------------------------------
# A - EXACTLY 20 POINTS
# ------------------------------------------------------------

A_letter = np.vstack([

    line_points([0, 0], [1.2, 4], 7),

    line_points([1.2, 4], [2.4, 0], 7),

    line_points([0.55, 1.8], [1.85, 1.8], 6)
])


# ------------------------------------------------------------
# G - EXACTLY 20 POINTS
# ------------------------------------------------------------

G_letter = np.array([
    [2.4, 4.0],
    [1.7, 4.0],
    [1.0, 3.9],
    [0.4, 3.5],
    [0.0, 2.9],
    [0.0, 2.2],
    [0.0, 1.5],
    [0.2, 0.8],
    [0.7, 0.3],
    [1.3, 0.0],
    [2.0, 0.2],
    [2.5, 0.7],
    [2.7, 1.3],
    [2.7, 1.9],
    [2.0, 1.9],
    [1.5, 1.9],
    [2.7, 2.6],
    [2.7, 3.2],
    [2.6, 3.7],
    [2.2, 3.9]
])


# ------------------------------------------------------------
# H - EXACTLY 20 POINTS
# ------------------------------------------------------------

H = np.vstack([

    line_points([0, 0], [0, 4], 7),

    line_points([0, 2], [2, 2], 6),

    line_points([2, 4], [2, 0], 7)
])


# ------------------------------------------------------------
# U - EXACTLY 20 POINTS
# ------------------------------------------------------------

U = np.vstack([

    line_points([0, 4], [0, 1], 7),

    line_points([0, 1], [1.2, 0], 3),

    line_points([1.2, 0], [2.4, 1], 3),

    line_points([2.4, 1], [2.4, 4], 7)
])


# ============================================================
# CHECK NUMBER OF TARGET POINTS
# ============================================================

print("\nNumber of target points:")

print("R:", len(R))
print("A:", len(A_letter))
print("G:", len(G_letter))
print("H:", len(H))
print("U:", len(U))


# ============================================================
# PLOT ALL FIVE TARGET FORMATIONS
# ============================================================

formations = [
    R,
    A_letter,
    G_letter,
    H,
    U
]

letters = [
    "R",
    "A",
    "G",
    "H",
    "U"
]


fig, axes = plt.subplots(
    1,
    5,
    figsize=(15, 4)
)


for ax, points, letter in zip(
    axes,
    formations,
    letters
):

    ax.scatter(
        points[:, 0],
        points[:, 1],
        s=80
    )

    ax.set_title(
        letter,
        fontsize=18
    )

    ax.set_aspect("equal")

    ax.grid(True)


plt.tight_layout()
plt.show()


# ============================================================
# STEP 4: FORMATION CONTROL
# RANDOM POSITION -> R
# ============================================================


# Current agent positions
X = X0.copy()

# Target is R
target = R.copy()


# Simulation parameters
dt = 0.05
steps = 300


# Store complete trajectory
trajectory = np.zeros(
    (steps + 1, N, 2)
)

trajectory[0] = X


# ------------------------------------------------------------
# Formation-control simulation
# ------------------------------------------------------------

for k in range(steps):

    U_control = np.zeros(
        (N, 2)
    )

    for i in range(N):

        # Use the communication graph
        for j in G_graph.neighbors(i):

            U_control[i] += (
                -(X[i] - X[j])
                + (target[i] - target[j])
            )

        # Pull agent toward its own target
        U_control[i] += (
            -(X[i] - target[i])
        )


    # Update agent positions
    X = X + dt * U_control


    # Store positions
    trajectory[k + 1] = X


print("\nFormation-control simulation complete.")

print(
    "Trajectory shape:",
    trajectory.shape
)


# ============================================================
# STEP 5: FINAL R FORMATION
# ============================================================

plt.figure(figsize=(7, 6))


# Initial positions
plt.scatter(
    X0[:, 0],
    X0[:, 1],
    s=60,
    alpha=0.3,
    label="Initial positions"
)


# Target R
plt.scatter(
    R[:, 0],
    R[:, 1],
    s=120,
    marker="x",
    label="Target R"
)


# Final agent positions
plt.scatter(
    X[:, 0],
    X[:, 1],
    s=100,
    label="Final positions"
)


plt.xlabel("x position")
plt.ylabel("y position")

plt.title(
    "Formation Control: Random Position → R"
)

plt.axis("equal")
plt.grid(True)
plt.legend()

plt.show()

# ============================================================
# STEP 5 + STEP 6
# RAGHU FORMATION CONTROL
# CLEAN ANIMATION - NO THREADS / NO EDGES
#
# RANDOM -> R -> A -> G -> H -> U
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML, display


# ============================================================
# STEP 5: FORMATION CONTROL
# ============================================================

print("======================================")
print("STEP 5: FORMATION CONTROL")
print("======================================")


# ------------------------------------------------------------
# Make sure graph variable exists
# ------------------------------------------------------------

if "G_graph" not in globals():

    if "G" in globals():
        G_graph = G
    else:
        raise NameError(
            "Communication graph not found. "
            "Please run Steps 1-4 first."
        )


# ------------------------------------------------------------
# Number of agents
# ------------------------------------------------------------

N = 20


# ------------------------------------------------------------
# Formation names
# ------------------------------------------------------------

letters = [
    "R",
    "A",
    "G",
    "H",
    "U"
]


# ------------------------------------------------------------
# Target formations
# ------------------------------------------------------------

targets = [
    np.asarray(R, dtype=float),
    np.asarray(A_letter, dtype=float),
    np.asarray(G_letter, dtype=float),
    np.asarray(H, dtype=float),
    np.asarray(U, dtype=float)
]


# ============================================================
# CHECK TARGETS
# ============================================================

print("\nTarget formation sizes:")

for letter, target in zip(letters, targets):

    print(
        f"{letter}: {target.shape[0]} points"
    )


# Make sure every formation has exactly 20 points

for letter, target in zip(letters, targets):

    if target.shape != (N, 2):

        raise ValueError(
            f"Formation {letter} has shape "
            f"{target.shape}. "
            f"Expected ({N}, 2)."
        )


# ============================================================
# SIMULATION SETTINGS
# ============================================================

frames_per_letter = 20

dt = 0.08

k_target = 3.5

k_graph = 0.35


# ============================================================
# INITIAL POSITION
# ============================================================

X = X0.copy()


# ============================================================
# STORAGE
# ============================================================

trajectory = []

trajectory_letters = []


# ============================================================
# SMOOTHSTEP
# ============================================================

def smoothstep(t):

    return (
        3 * t**2
        - 2 * t**3
    )


# ============================================================
# FORMATION TRANSITION
# ============================================================

def create_transition(
    X_start,
    target_start,
    target_end,
    current_letter
):

    X_current = X_start.copy()


    for frame in range(frames_per_letter):

        # ----------------------------------------------------
        # Normalized time
        # ----------------------------------------------------

        t = frame / (
            frames_per_letter - 1
        )


        # ----------------------------------------------------
        # Smooth movement
        # ----------------------------------------------------

        s = smoothstep(t)


        # ----------------------------------------------------
        # Desired intermediate formation
        # ----------------------------------------------------

        desired = (
            (1 - s) * target_start
            + s * target_end
        )


        # ----------------------------------------------------
        # Formation control
        # ----------------------------------------------------

        control = np.zeros(
            (N, 2)
        )


        for i in range(N):

            # -----------------------------------------------
            # Attraction toward target
            # -----------------------------------------------

            control[i] += (
                k_target
                * (
                    desired[i]
                    - X_current[i]
                )
            )


            # -----------------------------------------------
            # Graph-based coordination
            # -----------------------------------------------

            for j in G_graph.neighbors(i):

                error = (
                    (
                        desired[i]
                        - desired[j]
                    )
                    -
                    (
                        X_current[i]
                        - X_current[j]
                    )
                )


                control[i] += (
                    k_graph
                    * error
                )


        # ----------------------------------------------------
        # Update position
        # ----------------------------------------------------

        X_current = (
            X_current
            + dt * control
        )


        # ----------------------------------------------------
        # Make final frame exactly equal to target
        # ----------------------------------------------------

        if frame == frames_per_letter - 1:

            X_current = target_end.copy()


        # ----------------------------------------------------
        # Save frame
        # ----------------------------------------------------

        trajectory.append(
            X_current.copy()
        )


        trajectory_letters.append(
            current_letter
        )


    return X_current


# ============================================================
# RANDOM -> R
# ============================================================

print("\nFormation sequence:")

print("Random positions -> R")

X = create_transition(
    X,
    X0,
    targets[0],
    "R"
)


# ============================================================
# R -> A
# ============================================================

print("R -> A")

X = create_transition(
    X,
    targets[0],
    targets[1],
    "A"
)


# ============================================================
# A -> G
# ============================================================

print("A -> G")

X = create_transition(
    X,
    targets[1],
    targets[2],
    "G"
)


# ============================================================
# G -> H
# ============================================================

print("G -> H")

X = create_transition(
    X,
    targets[2],
    targets[3],
    "H"
)


# ============================================================
# H -> U
# ============================================================

print("H -> U")

X = create_transition(
    X,
    targets[3],
    targets[4],
    "U"
)


# ============================================================
# CONVERT TRAJECTORY
# ============================================================

trajectory = np.asarray(
    trajectory
)


print("\n======================================")
print("STEP 5 COMPLETE")
print("======================================")

print(
    "Trajectory shape:",
    trajectory.shape
)

print(
    "Total frames:",
    len(trajectory)
)

print(
    "Animation order:"
)

print(
    "R -> A -> G -> H -> U"
)


# ============================================================
# STEP 6: CLEAN ANIMATION
# ============================================================

print("\nCreating clean animation...")


# ------------------------------------------------------------
# Figure
# ------------------------------------------------------------

fig, ax = plt.subplots(
    figsize=(8, 7)
)


# ------------------------------------------------------------
# Dark background
# ------------------------------------------------------------

fig.patch.set_facecolor(
    "#111111"
)

ax.set_facecolor(
    "#111111"
)


# ------------------------------------------------------------
# Axes
# ------------------------------------------------------------

ax.set_xlim(
    -1,
    4
)

ax.set_ylim(
    -1,
    5
)

ax.set_aspect(
    "equal"
)


ax.set_xlabel(
    "x position",
    color="white",
    fontsize=11
)

ax.set_ylabel(
    "y position",
    color="white",
    fontsize=11
)


ax.tick_params(
    colors="white"
)


for spine in ax.spines.values():

    spine.set_color(
        "white"
    )


ax.grid(
    True,
    alpha=0.15
)


# ============================================================
# INITIAL AGENT POSITIONS
# ============================================================

positions = trajectory[0]


# ============================================================
# AGENTS
# ============================================================

agents = ax.scatter(
    positions[:, 0],
    positions[:, 1],
    s=130,
    edgecolors="white",
    linewidths=0.8
)


# ============================================================
# AGENT NUMBERS
# ============================================================

agent_labels = []


for i in range(N):

    label = ax.text(
        positions[i, 0] + 0.06,
        positions[i, 1] + 0.06,
        str(i),
        fontsize=8,
        color="white"
    )

    agent_labels.append(
        label
    )


# ============================================================
# TITLE
# ============================================================

ax.set_title(
    "FORMATION CONTROL OF RAGHU",
    color="white",
    fontsize=17,
    fontweight="bold",
    pad=15
)


# ============================================================
# CURRENT LETTER
# ============================================================

letter_text = ax.text(
    0.5,
    0.94,
    "R",
    transform=ax.transAxes,
    ha="center",
    va="center",
    fontsize=25,
    fontweight="bold",
    color="white"
)


# ============================================================
# FORMATION NUMBER
# ============================================================

progress_text = ax.text(
    0.5,
    0.89,
    "Formation 1 / 5",
    transform=ax.transAxes,
    ha="center",
    va="center",
    fontsize=10,
    color="white",
    alpha=0.8
)


# ============================================================
# UPDATE FUNCTION
# ============================================================

def update(frame):

    # --------------------------------------------------------
    # Current positions
    # --------------------------------------------------------

    positions = trajectory[frame]


    # --------------------------------------------------------
    # Move agents
    # --------------------------------------------------------

    agents.set_offsets(
        positions
    )


    # --------------------------------------------------------
    # Move agent numbers
    # --------------------------------------------------------

    for i in range(N):

        agent_labels[i].set_position(
            (
                positions[i, 0] + 0.06,
                positions[i, 1] + 0.06
            )
        )


    # ========================================================
    # CURRENT LETTER
    # ========================================================

    letter_index = (
        frame // frames_per_letter
    )


    # Safety check

    letter_index = min(
        letter_index,
        len(letters) - 1
    )


    current_letter = letters[
        letter_index
    ]


    # --------------------------------------------------------
    # Change large letter
    # --------------------------------------------------------

    letter_text.set_text(
        current_letter
    )


    # --------------------------------------------------------
    # Change formation number
    # --------------------------------------------------------

    progress_text.set_text(
        f"Formation {letter_index + 1} / 5"
    )


    return (
        [agents]
        + agent_labels
        + [
            letter_text,
            progress_text
        ]
    )


# ============================================================
# CREATE ANIMATION
# ============================================================

animation = FuncAnimation(
    fig,
    update,
    frames=len(trajectory),
    interval=50,
    blit=False,
    repeat=True
)


# ============================================================
# CLOSE STATIC FIGURE
# ============================================================

plt.close(fig)


# ============================================================
# DISPLAY INLINE
# ============================================================

print("\n======================================")
print("STEP 6 COMPLETE")
print("======================================")

print(
    "Displaying clean R -> A -> G -> H -> U animation..."
)


display(
    HTML(
        animation.to_html5_video()
    )
)